### ISSUE TITLE
Sign out button missing

### ISSUE THREAD

**Issue by joanjoantan** [bfit/bfit-tracker-app#3]
It is not allow me sign out after I sign in

**Comment by joanjoantan** [comment]
Having the error when user choose don't allow access to location.

**Comment by divyesh26** [comment]
For the user to log in to another Google account?

**Comment by DiogoTheCoder** [comment]
> 
> 
> It is not allow me sign out after I sign in

Hi @joanjoantan 👋 ,

Thanks for bringing this to our attention. I can inform you that we as a team have discussed this and have decided that we will be implementing the ability for users' to log out. The plan is to allow the user to press on the top most Card in the Home tab.

For example:
![image](https://user-images.githubusercontent.com/31896387/62573553-370d5c00-b88e-11e9-8d8f-247c53a41cc4.png)

Upon clicking an alert dialog will appear confirming whether the user would wish to log out and if so they'll be logged out and returned to the Splash Screen.

The team has already started working on this and you should expect to see this change coming soon, of course this will depend on the length of time it takes to develop and merge the eventual PR 🤞 .

Many thanks,

@DiogoTheCoder

**Comment by DiogoTheCoder** [comment]
Congratulations @joanjoantan 🎉 a PR has been submitted to resolve this issue. https://github.com/bfit/bfit-tracker-app/pull/5
